development:
  adapter:  postgresql
  encoding: utf8
  reconnect: false
  pool: 8
  encoding: unicode
  host: localhost
  username: postgres
  password: root110120
  database: wiki_development

test:
  adapter:  postgresql
  encoding: utf8
  reconnect: false
  pool: 8
  encoding: unicode
  host: localhost
  username: postgres
  password: root110120
  database: wiki_test

production:
  adapter:  postgresql
  encoding: utf8
  reconnect: false
  pool: 8
  encoding: unicode
  url: <%= ENV['POSTGRESQL_URL'] %>
  database: wiki_production
