development:
  clients:
    default:
      database: wiki_production
      #username: <%= ENV['MONGODB_USER'] %>
      #password: <%= ENV['MONGODB_PWD'] %>
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  clients:
    default:
      database: wiki_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
production:
  clients:
    default:
      database: wiki_production
      #username: <%= ENV['MONGODB_USER'] %>
      #password: <%= ENV['MONGODB_PWD'] %>
      hosts:
        - localhost:27017
      options:
        consistency: :strong
